### PR TITLE
Enable use of custom input tensor

### PR DESCRIPTION
**Pull request by daniegr**

### CODE REVIEW

**Comment by daniegr** [comment]
Made small modifications to the model script to facilitate use of custom input tensor

**Comment by daniegr** [comment]
@qubvel Possible to include this modification?

**Comment by qubvel** [comment]
Hi @daniegr thanks for PR!
Yes, it is possible, could you also add this functionality to `tf.keras` branch?

**Comment by daniegr** [comment]
@qubvel Absolutely! You may find it here: #30

**Pull request merged**
