### PR TITLE
native tensorflow port

### PR DESCRIPTION
**Pull request by mattiavarile**
code has been modified in order to work with tensorflow.keras and tensorflow eager.

### CODE REVIEW

**Comment by mattiavarile** [comment]
update

**Comment by qubvel** [comment]
Hi @mattiavarile 
I did not try to use tf.keras. Is it fully compatible with keras?
Should not it be like keras_applications with optional backend specification?

**Comment by mattiavarile** [comment]
Hi @qubvel 

1. Yes, as far as I know is fully compatible and integrated.
2. If your objective is to integrate the repository into keras_application and make the code compatible with other backends, then it would be better to avoid using tf.keras and not merging my repository in master branch. Otherwise I think is better to use the native tensorflow integration of keras, in order to leverage the upcoming tf2.0 capabilities such as eager executions.

**Comment by sdll** [comment]
@qubvel, @mattiavarile, could you please close this PR and merge the code into a separate branch instead? This will serve as a compromise between the two approaches that @mattiavarile has mentioned, enabling access to all the advantages that tf.keras provides.

**Comment by sdll** [comment]
@qubvel, I have added several improvements to this PR (adding support for the export to SavedModel in the converter, for example). Could you please create a new branch, say `tf-keras`, so that there was a tf.keras implementation as well?

**Pull request closed without merging**
